// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuildRecord = "build_records"

// BuildRecord mapped from table <build_records>
type BuildRecord struct {
	ID         int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Pid        *int32     `gorm:"column:pid" json:"pid"`
	Status     *int32     `gorm:"column:status" json:"status"`
	Bin        *string    `gorm:"column:bin" json:"bin"`
	Parameters *string    `gorm:"column:parameters" json:"parameters"`
	WorkDir    *string    `gorm:"column:work_dir" json:"workDir"`
	CreatedAt  *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"`
}

// TableName BuildRecord's table name
func (*BuildRecord) TableName() string {
	return TableNameBuildRecord
}
