// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLog = "logs"

// Log mapped from table <logs>
type Log struct {
	ID        int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"Id"`
	BuildID   *int32     `gorm:"column:build_id" json:"BuildId"`
	Content   *string    `gorm:"column:content" json:"Content"`
	CreatedAt *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"CreatedAt"`
}

// TableName Log's table name
func (*Log) TableName() string {
	return TableNameLog
}
